#!/usr/bin/python

# MakeTOC -- Finds major (linkd) links in an emacs lisp file
#            and creates a linked table of contents in an
#            emacs lisp comment.

# Currently requires python 2.6 but it should be downgraded!

import fileinput
import re

tagPattern = re.compile('^;+\(@\*\s+\"(.*)\"\)\s*;+')
toc_names = []

for line in fileinput.input():
    m = tagPattern.match(line)
    if m:
        toc_names.append(m.group(1))

for num, tag in enumerate(toc_names, start=1):
    print ';; {0:2d}. (@> "{1:s}")'.format(num, tag)

print "\n\n"

